apiVersion: v1
kind: Pod
metadata:
  name: custom-controller-pod
spec:
  nodeSelector:
    dedicated: master
  containers:
  - image: custom_controller_image:1.1
    name: custom-controller-pod
    volumeMounts:
    - mountPath: /root/.kube
      name: test-volume
    command: ["./root/pod_custom_controller"]
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /opt/custom_controller_config/
      # this field is optional
      type: Directory
